- name: install yum package
  hosts: linux
  tasks:
           - name: install yum package
             yum:
                      name: tree
                      state: present
                      update_cache: true
             become: true
             when: ansible_os_family == 'RedHat'
                    
